name: PR Target Branch Check

on:
  pull_request_target:
    branches:
      - main

permissions:
  pull-requests: write
  issues: write

jobs:
  check-target:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR base and head branch
        uses: actions/github-script@v5
        if: github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref != 'dev'
        with:
          script: |
            const mainBranchUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/tree/main`;
            const devBranchUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/tree/dev`;
            const headBranch = `${{ github.event.pull_request.head.ref }}`;
            const headBranchUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/tree/${headBranch}`;
            const message = `🚨 Warning: This PR is targeting \`main\` from [\`${headBranch}\`](${headBranchUrl}). PRs should generally target [\`dev\`](${devBranchUrl}). Please check that you are merging to the correct branch. 🚨`;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
